"""Tests for packaging and import sanity — all runtime modules must be importable."""

from __future__ import annotations

import importlib

import pytest


_RUNTIME_MODULES = [
    "orchestrator",
    "orchestrator.cli",
    "orchestrator.pipeline",
    "orchestrator.yolo",
    "orchestrator.planner",
    "orchestrator.schemas",
    "orchestrator.chat_runtime",
    "orchestrator.session_state",
    "orchestrator.preflight",
    "orchestrator.logging_setup",
    "orchestrator.agent_status",
    "tui",
    "tui.session",
    "tui.commands",
    "tui.llm_chat",
    "tui.models",
    "tui.renderer",
    "tui.theme",
    "tui.thinking",
    "skills",
    "skills.models",
    "skills.registry",
    "skills.resolver",
    "skills.generator",
    "skills.executor",
    "skills.openclaw_adapter",
    "memory_skill",
    "memory_skill.reader",
    "memory_skill.writer",
    "memory_skill.models",
    "memory_skill.sync",
    "memory_skill.retriever",
    "memory_skill.always_remember",
    "repo_graph",
    "repo_graph.models",
    "repo_graph.scanner",
    "repo_graph.linker",
    "scope_engine",
    "scope_engine.engine",
    "scope_engine.models",
    "mutation_engine",
    "mutation_engine.engine",
    "mutation_engine.models",
    "agents",
    "agents.registry",
    "agents.router",
    "agents.detector",
    "agents.base",
    "agents.capabilities",
    "providers",
    "providers.base",
    "providers.registry",
    "providers.litellm_provider",
    "routing",
    "routing.classifier",
    "routing.router",
    "routing.cost_estimator",
    "tools",
    "tools.repo_auditor",
    "tools.repo_mapper",
    "tools.context_packer",
    "tools.build_detector",
    "mcp_server",
    "mcp_server.server",
    "execution",
    "execution.backend",
    "execution.models",
    "discovery",
    "discovery.hardware",
    "discovery.toolchain",
    "discovery.profile",
    "recommendation",
    "recommendation.catalog",
    "recommendation.engine",
    "recommendation.models",
    "config",
    "config.config_loader",
]


@pytest.mark.parametrize("module_name", _RUNTIME_MODULES)
def test_import(module_name: str):
    """Every runtime module must be importable without error."""
    importlib.import_module(module_name)
