from __future__ import annotations

from recommendation.models import LLMBundle

_CATALOG: list[LLMBundle] = [
    # ── CodeLlama family ──────────────────────────────────────────────
    LLMBundle(
        model_id="codellama-7b-q4",
        display_name="CodeLlama 7B (Q4_K_M)",
        family="codellama",
        parameter_count="7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=3.8,
        estimated_ram_gb=5.6,
        estimated_vram_gb=4.8,
        recommended_use_cases=["code completion", "infilling", "small-project assistance"],
        download_url="https://ollama.com/library/codellama:7b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="codellama-13b-q4",
        display_name="CodeLlama 13B (Q4_K_M)",
        family="codellama",
        parameter_count="13B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=7.4,
        estimated_ram_gb=9.8,
        estimated_vram_gb=8.6,
        recommended_use_cases=["code completion", "refactoring", "code review"],
        download_url="https://ollama.com/library/codellama:13b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="codellama-34b-q4",
        display_name="CodeLlama 34B (Q4_K_M)",
        family="codellama",
        parameter_count="34B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=19.0,
        estimated_ram_gb=22.0,
        estimated_vram_gb=20.0,
        recommended_use_cases=["complex code generation", "multi-file refactoring", "architecture"],
        download_url="https://ollama.com/library/codellama:34b-instruct-q4_K_M",
    ),
    # ── DeepSeek Coder family ─────────────────────────────────────────
    LLMBundle(
        model_id="deepseek-coder-1.3b-q4",
        display_name="DeepSeek Coder 1.3B (Q4_K_M)",
        family="deepseek-coder",
        parameter_count="1.3B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=0.9,
        estimated_ram_gb=1.5,
        estimated_vram_gb=1.2,
        recommended_use_cases=["lightweight code completion", "quick suggestions"],
        download_url="https://ollama.com/library/deepseek-coder:1.3b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="deepseek-coder-6.7b-q4",
        display_name="DeepSeek Coder 6.7B (Q4_K_M)",
        family="deepseek-coder",
        parameter_count="6.7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=3.8,
        estimated_ram_gb=5.2,
        estimated_vram_gb=4.5,
        recommended_use_cases=["code completion", "unit test generation", "docstrings"],
        download_url="https://ollama.com/library/deepseek-coder:6.7b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="deepseek-coder-v2-16b-q4",
        display_name="DeepSeek Coder V2 16B (Q4_K_M)",
        family="deepseek-coder",
        parameter_count="16B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=9.1,
        estimated_ram_gb=11.5,
        estimated_vram_gb=10.2,
        recommended_use_cases=["advanced code generation", "multi-language support", "reasoning"],
        download_url="https://ollama.com/library/deepseek-coder-v2:16b-lite-instruct-q4_K_M",
        notes="MoE architecture — faster than dense models of similar quality.",
    ),
    LLMBundle(
        model_id="deepseek-coder-33b-q4",
        display_name="DeepSeek Coder 33B (Q4_K_M)",
        family="deepseek-coder",
        parameter_count="33B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=18.5,
        estimated_ram_gb=21.0,
        estimated_vram_gb=19.5,
        recommended_use_cases=[
            "complex code generation",
            "large codebase reasoning",
            "refactoring",
        ],
        download_url="https://ollama.com/library/deepseek-coder:33b-instruct-q4_K_M",
    ),
    # ── Qwen 2.5 Coder family ────────────────────────────────────────
    LLMBundle(
        model_id="qwen2.5-coder-1.5b-q4",
        display_name="Qwen 2.5 Coder 1.5B (Q4_K_M)",
        family="qwen2.5-coder",
        parameter_count="1.5B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=1.0,
        estimated_ram_gb=1.8,
        estimated_vram_gb=1.4,
        recommended_use_cases=["lightweight autocomplete", "quick inline suggestions"],
        download_url="https://ollama.com/library/qwen2.5-coder:1.5b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="qwen2.5-coder-7b-q4",
        display_name="Qwen 2.5 Coder 7B (Q4_K_M)",
        family="qwen2.5-coder",
        parameter_count="7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=4.4,
        estimated_ram_gb=5.8,
        estimated_vram_gb=5.0,
        recommended_use_cases=["code completion", "test generation", "code review"],
        download_url="https://ollama.com/library/qwen2.5-coder:7b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="qwen2.5-coder-14b-q4",
        display_name="Qwen 2.5 Coder 14B (Q4_K_M)",
        family="qwen2.5-coder",
        parameter_count="14B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=8.2,
        estimated_ram_gb=10.5,
        estimated_vram_gb=9.2,
        recommended_use_cases=["advanced code generation", "architecture design", "debugging"],
        download_url="https://ollama.com/library/qwen2.5-coder:14b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="qwen2.5-coder-32b-q4",
        display_name="Qwen 2.5 Coder 32B (Q4_K_M)",
        family="qwen2.5-coder",
        parameter_count="32B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=18.5,
        estimated_ram_gb=21.5,
        estimated_vram_gb=19.8,
        recommended_use_cases=["complex multi-file generation", "large codebase refactoring"],
        download_url="https://ollama.com/library/qwen2.5-coder:32b-instruct-q4_K_M",
        notes="Top-tier open coding model as of early 2025.",
    ),
    # ── Mistral / Codestral ───────────────────────────────────────────
    LLMBundle(
        model_id="mistral-7b-q4",
        display_name="Mistral 7B (Q4_K_M)",
        family="mistral",
        parameter_count="7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=8192,
        specialization="general",
        estimated_disk_gb=4.1,
        estimated_ram_gb=5.6,
        estimated_vram_gb=4.8,
        recommended_use_cases=["general chat", "summarisation", "light coding"],
        download_url="https://ollama.com/library/mistral:7b-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="codestral-22b-q4",
        display_name="Codestral 22B (Q4_K_M)",
        family="codestral",
        parameter_count="22B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=32768,
        specialization="coding",
        estimated_disk_gb=12.5,
        estimated_ram_gb=15.0,
        estimated_vram_gb=13.5,
        recommended_use_cases=["code generation", "FIM completion", "multi-language coding"],
        download_url="https://ollama.com/library/codestral:22b-v0.1-q4_K_M",
        notes="Mistral's dedicated code model with 80+ language support.",
    ),
    # ── StarCoder2 family ─────────────────────────────────────────────
    LLMBundle(
        model_id="starcoder2-3b-q4",
        display_name="StarCoder2 3B (Q4_K_M)",
        family="starcoder2",
        parameter_count="3B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=1.8,
        estimated_ram_gb=2.8,
        estimated_vram_gb=2.4,
        recommended_use_cases=["fast autocomplete", "simple code infilling"],
        download_url="https://ollama.com/library/starcoder2:3b-q4_K_M",
    ),
    LLMBundle(
        model_id="starcoder2-7b-q4",
        display_name="StarCoder2 7B (Q4_K_M)",
        family="starcoder2",
        parameter_count="7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=4.2,
        estimated_ram_gb=5.6,
        estimated_vram_gb=4.9,
        recommended_use_cases=["code completion", "code explanation"],
        download_url="https://ollama.com/library/starcoder2:7b-q4_K_M",
    ),
    LLMBundle(
        model_id="starcoder2-15b-q4",
        display_name="StarCoder2 15B (Q4_K_M)",
        family="starcoder2",
        parameter_count="15B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=16384,
        specialization="coding",
        estimated_disk_gb=8.5,
        estimated_ram_gb=10.8,
        estimated_vram_gb=9.6,
        recommended_use_cases=["code generation", "repository-level completion"],
        download_url="https://ollama.com/library/starcoder2:15b-q4_K_M",
    ),
    # ── Phi-3 / Phi-3.5 family ────────────────────────────────────────
    LLMBundle(
        model_id="phi3-mini-q4",
        display_name="Phi-3 Mini 3.8B (Q4_K_M)",
        family="phi3",
        parameter_count="3.8B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=4096,
        specialization="general",
        estimated_disk_gb=2.2,
        estimated_ram_gb=3.5,
        estimated_vram_gb=3.0,
        recommended_use_cases=["general chat", "light reasoning", "quick prototyping"],
        download_url="https://ollama.com/library/phi3:mini-4k-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="phi3.5-mini-q4",
        display_name="Phi-3.5 Mini 3.8B (Q4_K_M)",
        family="phi3",
        parameter_count="3.8B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=8192,
        specialization="general",
        estimated_disk_gb=2.3,
        estimated_ram_gb=3.6,
        estimated_vram_gb=3.1,
        recommended_use_cases=["general chat", "multilingual", "reasoning"],
        download_url="https://ollama.com/library/phi3.5:3.8b-mini-instruct-q4_K_M",
        notes="Improved over Phi-3 Mini with longer context and better multilingual.",
    ),
    LLMBundle(
        model_id="phi3-small-q4",
        display_name="Phi-3 Small 7B (Q4_K_M)",
        family="phi3",
        parameter_count="7B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=8192,
        specialization="general",
        estimated_disk_gb=4.1,
        estimated_ram_gb=5.5,
        estimated_vram_gb=4.8,
        recommended_use_cases=["general assistance", "code understanding", "summarisation"],
        download_url="https://ollama.com/library/phi3:small-8k-instruct-q4_K_M",
    ),
    LLMBundle(
        model_id="phi3-medium-q4",
        display_name="Phi-3 Medium 14B (Q4_K_M)",
        family="phi3",
        parameter_count="14B",
        quantization="Q4_K_M",
        runtime="ollama",
        context_size=8192,
        specialization="general",
        estimated_disk_gb=7.9,
        estimated_ram_gb=10.2,
        estimated_vram_gb=9.0,
        recommended_use_cases=["complex reasoning", "code generation", "analysis"],
        download_url="https://ollama.com/library/phi3:medium-4k-instruct-q4_K_M",
    ),
]


def get_catalog() -> list[LLMBundle]:
    """Return the full catalog of known local-LLM bundles."""
    return list(_CATALOG)
