"""Render .bat templates with string.Template substitution and security scanning."""

from __future__ import annotations

import os
import re
from pathlib import Path
from string import Template

from orchestrator.schemas import AgentProfile

_REPO_ROOT = Path(__file__).parent.parent
_DEFAULT_TEMPLATES_DIR = _REPO_ROOT / "jobs" / "templates"
_DEFAULT_GENERATED_DIR = _REPO_ROOT / "jobs" / "generated"

_SHELL_META_RE = re.compile(r"[&|<>;]")

_TRUSTED_VARIABLE_KEYS = frozenset({"BUILD_COMMANDS", "TEST_COMMANDS", "AGENT_INVOCATION"})


class TemplateRenderer:
    """Reads ``.bat.template`` files, substitutes variables, and writes output."""

    def __init__(
        self,
        templates_dir: Path | None = None,
        generated_dir: Path | None = None,
    ) -> None:
        self._templates_dir = templates_dir or _DEFAULT_TEMPLATES_DIR
        self._generated_dir = generated_dir or _DEFAULT_GENERATED_DIR

    def render(
        self,
        template_name: str,
        variables: dict[str, str],
        output_filename: str | None = None,
    ) -> Path:
        """Substitute *variables* into *template_name* and write the result.

        Returns the path to the generated ``.bat`` file.
        """
        template_path = self._templates_dir / template_name
        content = template_path.read_text(encoding="utf-8")

        self._validate_variable_values(variables)

        rendered = Template(content).safe_substitute(variables)

        self._generated_dir.mkdir(parents=True, exist_ok=True)
        out_name = output_filename or template_name.replace(".template", "")
        out_path = self._generated_dir / out_name
        out_path.write_text(rendered, encoding="utf-8")
        return out_path

    def render_for_profile(
        self,
        profile: AgentProfile,
        job_id: str,
        *,
        agent_invocation: str = "",
        agent_id: str = "none",
        agent_display_name: str = "No Agent",
    ) -> Path:
        """Build variables from *profile* and render its template.

        The ``agent_invocation`` parameter is the fully-built command line
        for the selected agent CLI.  It is injected as ``$AGENT_INVOCATION``
        in agent-aware templates (e.g. ``agent_task.bat.template``).

        For backwards compatibility with Cursor-specific templates, the
        legacy ``CURSOR_CLI_PATH`` and ``CURSOR_PROMPT`` variables are
        still populated.
        """
        artifact_dir = _REPO_ROOT / "artifacts" / job_id

        variables: dict[str, str] = {
            "JOB_ID": job_id,
            "OBJECTIVE": profile.variables.get("OBJECTIVE", profile.description),
            "WORKING_DIR": profile.working_directory,
            "TIMEOUT_SECONDS": str(profile.timeout_seconds),
            "ARTIFACT_DIR": str(artifact_dir),
            "BUILD_COMMANDS": self._format_commands(profile.build_commands, "BUILD"),
            "TEST_COMMANDS": self._format_commands(profile.test_commands, "TEST"),
            # Agent-aware variables
            "AGENT_ID": agent_id,
            "AGENT_DISPLAY_NAME": agent_display_name,
            "AGENT_INVOCATION": agent_invocation,
            # Legacy Cursor variables for backwards compatibility
            "CURSOR_CLI_PATH": os.environ.get("CURSOR_CLI_PATH", "cursor"),
            "CURSOR_PROMPT": profile.variables.get("CURSOR_PROMPT", ""),
        }

        return self.render(
            profile.prompt_template,
            variables,
            output_filename=f"{job_id}.bat",
        )

    # ------------------------------------------------------------------

    @staticmethod
    def _format_commands(commands: list[str], label: str) -> str:
        """Format a command list into the multi-line .bat echo+run pattern."""
        if not commands:
            return ""
        lines: list[str] = []
        for cmd in commands:
            lines.append(f'echo [{label}] Running: {cmd} >> "%STDOUT_LOG%"')
            lines.append(f'{cmd} >> "%STDOUT_LOG%" 2>> "%STDERR_LOG%"')
            lines.append("if errorlevel 1 set EXIT_CODE=1")
        return "\n".join(lines)

    @staticmethod
    def _validate_variable_values(variables: dict[str, str]) -> None:
        """Reject variable *values* that inject shell metacharacters.

        Variables in ``_TRUSTED_VARIABLE_KEYS`` (e.g. BUILD_COMMANDS,
        TEST_COMMANDS, AGENT_INVOCATION) are generated by internal code
        that intentionally uses redirection syntax, so they are exempt.
        """
        for key, value in variables.items():
            if key in _TRUSTED_VARIABLE_KEYS:
                continue
            if _SHELL_META_RE.search(str(value)):
                raise ValueError(
                    f"Potential injection in variable {key!r}: "
                    f"shell metacharacters found in value: {value!r}"
                )
